/**
 * Types for authentication
 */

/**
 * Structure of a Zero-Knowledge Proof
 * This is a simplified version for demonstration purposes
 * In a real implementation, this would match the structure generated by snarkjs
 */
export interface ZKProof {
  proof: {
    pi_a?: string[];
    pi_b?: string[][];
    pi_c?: string[];
    protocol?: string;
    type?: string;
    value?: string;
  };
  publicSignals?: string[];
}

/**
 * Authentication response from the server
 */
export interface AuthResponse {
  success: boolean;
  message: string;
  uid?: string;
  recoveryPhrase?: string;
}